#token: 6670867019:AAFZwsnxb0sAP4XMRvUmJI5Lm8l5UCEAoZQ
token:
  6313743575:AAFcWeymKrcfKklGuAWlQtEzIM995T2kF9U
#webhook_url: https://toplinkbot.com/bot/notify
url:
  "https://toplinkbot.com/"
cert_file:
  "./cert/toplinkbot_com.crt"
key_file:
  "./cert/toplinkbot_com.pem"
database_url:
  "postgresql://postgres:@localhost:5432/postgres"
redis_url:
  "redis://localhost:6379/0"
mysql:
  address: 34.192.77.144:13306
  database: testdb
  user_name: root
  passwd: openIM123


